services:
  postgres:
    image: postgres:15
    container_name: employee-db
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: postgres  # Default PostgreSQL superuser
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
    # Persist PostgreSQL data
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend/employee-management-system
    container_name: employee-backend
    # Remove external port exposure - only nginx will access backend
    expose:
      - "8080"
    depends_on:  # Ensure backend is started after postgres start
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/employee_db
      SPRING_DATASOURCE_USERNAME: postgres  # Use default PostgreSQL superuser
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./backend/employee-management-system:/app
    working_dir: /app

  # Updated frontend service with nginx
  frontend:
    build: ./frontend
    container_name: employee-frontend
    ports:
      - "80:80"  # Expose nginx on port 80
    depends_on:
      - backend
  
volumes:
  postgres_data: