spring:
  application:
    name: employee-management-system

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/employee_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate} # Use 'validate' in production, not 'create-drop'
    show-sql: ${SPRING_JPA_SHOW_SQL:false} # Disable SQL logging in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': false
        '[jdbc.batch_size]': 20
        '[order_inserts]': true
        '[order_updates]': true
    defer-datasource-initialization: false

  sql:
    init:
      mode: never # Do not execute initialization scripts in production

  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:admin}
      password: ${SPRING_SECURITY_USER_PASSWORD}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true

# Logging Configuration
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:WARN}
    '[edu.uw.cs.zongzewu]': ${LOGGING_LEVEL_APP:INFO}
    '[org.springframework.security]': WARN
    '[org.springframework.jdbc]': WARN
    '[org.springframework.boot.sql.init]': WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/employee-management-system.log
    max-size: 10MB
    max-history: 30

# Swagger Configuration (disabled in production)
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: ${SPRINGDOC_API_DOCS_ENABLED:false}
  swagger-ui:
    path: /swagger-ui.html
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED:false}
    try-it-out-enabled: false
  show-actuator: false
  packages-to-scan: edu.uw.cs.zongzewu.employee_management_system.controller
  paths-to-match: /api/**

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 hours
  refresh-expiration: 604800000 # 7 days

# CORS Configuration
app:
  cors:
    allowed-origins: ${CORS_ORIGINS:https://404Inc.com}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

# Monitoring Configuration
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info}
      base-path: /actuator
  endpoint:
    health:
      show-details: ${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:when-authorized}
      show-components: when-authorized
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true