spring:
  application:
    name: employee-management-system

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/employee_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop  # recreate table every time restart the application
    show-sql: true      # Log SQL queries for debugging
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true  # Format SQL queries in logs
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      continue-on-error: false

  security:
    user:
      name: wu          # Default Spring Security user for development
      password: 123

server:
  port: 8080

logging:
  level:
    '[edu.uw.cs.zongzewu]': DEBUG
    '[org.springframework.security]': DEBUG
    '[org.springframework.jdbc.datasource.init]': DEBUG
    '[org.springframework.boot.sql.init]': DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
  show-actuator: false
  packages-to-scan: edu.uw.cs.zongzewu.employee_management_system.controller
  paths-to-match: /api/**

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890123456789012345678901234567890EXTRA}

# CORS config
app:
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000,http://localhost}